# Generated by Django 3.2.4 on 2021-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.CharField(blank=True, max_length=100, null=True)),
                ('category_b', models.CharField(blank=True, max_length=100, null=True)),
                ('category_c', models.CharField(blank=True, max_length=100, null=True)),
                ('category_d', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
