# Generated by Django 3.2.4 on 2021-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_calendar', '0004_money_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
